# Travis-CI configuration file for SuperTuxKart
#
# Configuration manual:
# http://docs.travis-ci.com/user/build-configuration/
#
sudo: false
language: cpp
compiler:
  - gcc
  - clang

os:
  - osx

matrix:
  fast_finish: true
  exclude:
    - compiler: gcc
      os: osx

env:
  matrix:
    - BUILD_TYPE="Debug"
    - BUILD_TYPE="Release"

  #wget "http://downloads.sourceforge.net/project/supertuxkart/SuperTuxKart%20Dependencies/OSX/DepsFrameworks0.9.2-64bits.zip";
  #unzip -a DepsFrameworks0.9.2-64bits.zip;
  #         sudo ln -s /System/Library/Frameworks/OpenGL.framework/Versions/A/Headers/ /usr/local/include/GL;

before_install:
  - 'if [ "$TRAVIS_OS_NAME" = "osx" ]; then
        echo "STARTING TO INSTALL PACKAGES";
        sudo mkdir -p /usr/local/include/;
        brew update;
        brew outdated cmake || brew upgrade cmake;
        brew install glib libpng libogg libvorbis openal-soft freetype fribidi;
        xcrun --show-sdk-path;
        ls -la /usr/include/freetype2;
        pkg-config --cflags freetype2;
        
        brew link glib;
        pwd;
        echo "ENDING TO INSTALL PACKAGES";
    fi'

before_script:
  - export THREADS=8

script:
  - mkdir "build"
  - cd "build"
  - cmake .. -DCMAKE_BUILD_TYPE=$BUILD_TYPE -DUSE_WIIUSE=0 -DFREETYPE_INCLUDE_DIRS=/usr/local/opt/freetype/include/freetype2 -DCHECK_ASSETS=off
  - make VERBOSE=1 -j $THREADS CPPFLAGS=`pkg-config --cflags freetype2`
