# Travis-CI configuration file for SuperTuxKart
#
# Configuration manual:
# http://docs.travis-ci.com/user/build-configuration/
#
sudo: false
language: cpp
compiler:
  - gcc
  - clang

os:
  - linux
  - osx

matrix:
  fast_finish: true
  exclude:
    - compiler: gcc
      os: osx

env:
  matrix:
    - BUILD_TYPE="Debug"
    - BUILD_TYPE="Release"

addons:
  apt:
    packages:
    - build-essential
    - libogg-dev
    - libvorbis-dev
    - libopenal-dev
    - libxxf86vm-dev
    - libcurl4-openssl-dev
    - libfribidi-dev
    - libbluetooth-dev
    - libgl1-mesa-dev
    - libglu1-mesa-dev
    - libglew-dev
    - cmake


before_install:
  - if [ "$TRAVIS_OS_NAME" = "osx" ]; then
        brew update;
        brew upgrade cmake;
        brew install libogg libvorbis openal-soft freetype fribidi;
    fi

before_script:
  - export THREADS=$((`nproc` + 1))
  - echo "THREADS = $THREADS"
  - if [ "$TRAVIS_OS_NAME" = "linux" ]; then
        free -mt;
    fi

script:
  - mkdir "build"
  - cd "build"
  - cmake .. -DCMAKE_BUILD_TYPE=$BUILD_TYPE -DCHECK_ASSETS=off
  - make VERBOSE=1 -j $THREADS
